"""ISO 9001-style defect report generator (JSON + Markdown + optional PDF)."""
from __future__ import annotations

import datetime as dt
import logging
from pathlib import Path
from typing import Iterable, Optional

logger = logging.getLogger(__name__)

ISO_TEMPLATE_MD = """# ISO 9001 Non-Conformance Report

**Report ID:** {report_id}
**Generated:** {timestamp}
**Inspection ID:** {inspection_id}
**Product:** {product}

## 1. Defect Summary

| # | Defect ID | Type | Severity | Confidence | Bounding Box |
|---|-----------|------|----------|------------|--------------|
{rows}

## 2. Specification Reference

{spec_block}

## 3. Severity Analysis

{severity_block}

## 4. Disposition Decision

**Decision:** **{decision}**

**Rationale:** {rationale}

## 5. Corrective Actions

{actions}

---
*Generated by Multimodal Manufacturing Quality Intelligence with Agentic Reporting.*
"""


class ISO9001ReportGenerator:
    def __init__(self, output_dir: str = "reports"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate(
        self,
        inspection_id: str,
        findings: Iterable[dict],
        spec_context,
        decision: str,
        rationale: str,
        product: str = "Generic Component",
    ) -> dict:
        findings = list(findings)
        ts = dt.datetime.utcnow().isoformat(timespec="seconds") + "Z"
        report_id = f"NCR-{dt.datetime.utcnow().strftime('%Y%m%d-%H%M%S')}"

        rows = "\n".join(
            f"| {i + 1} | {f['defect_id']} | {f['defect_type']} | {f['severity']} | {f['confidence']:.2f} | {f['bbox']} |"
            for i, f in enumerate(findings)
        ) or "| – | – | – | – | – | – |"

        spec_block = spec_context.text if getattr(spec_context, "text", "") else "_No matching specification snippet retrieved._"
        spec_sources = ", ".join(getattr(spec_context, "sources", [])) or "n/a"

        severity_block = "\n".join(
            f"- **{f['defect_id']}** ({f['defect_type']}): graded **{f['severity']}** "
            f"(score={f['severity_score']:.2f}, probs={f['severity_probs']})"
            for f in findings
        ) or "_No defects above the confidence threshold._"

        actions = self._actions_for(decision)

        md = ISO_TEMPLATE_MD.format(
            report_id=report_id,
            timestamp=ts,
            inspection_id=inspection_id,
            product=product,
            rows=rows,
            spec_block=spec_block + f"\n\n*Sources:* {spec_sources}",
            severity_block=severity_block,
            decision=decision,
            rationale=rationale,
            actions=actions,
        )

        md_path = self.output_dir / f"{report_id}.md"
        md_path.write_text(md, encoding="utf-8")

        pdf_path = self._try_render_pdf(md, report_id)

        report_payload = {
            "report_id": report_id,
            "inspection_id": inspection_id,
            "timestamp": ts,
            "product": product,
            "decision": decision,
            "rationale": rationale,
            "findings": findings,
            "spec_sources": getattr(spec_context, "sources", []),
            "markdown_path": str(md_path),
            "pdf_path": str(pdf_path) if pdf_path else None,
        }
        logger.info("ISO 9001 report written: %s", md_path)
        return report_payload

    @staticmethod
    def _actions_for(decision: str) -> str:
        decision = decision.upper()
        if decision == "PASS":
            return "- Release to next workstation.\n- Log inspection to MES."
        if decision == "QUARANTINE":
            return (
                "- Move unit to quarantine area.\n"
                "- Notify QA engineer for manual disposition.\n"
                "- Trigger ERP WIP status update.")
        if decision == "REWORK":
            return "- Route unit to rework cell.\n- Tag with NCR ID.\n- Schedule re-inspection."
        return "- Scrap unit per ISO 9001 §8.7.\n- Update yield metrics.\n- Trigger root-cause analysis (5-Why)."

    def _try_render_pdf(self, markdown: str, report_id: str) -> Optional[Path]:
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.pdfgen import canvas
            pdf_path = self.output_dir / f"{report_id}.pdf"
            c = canvas.Canvas(str(pdf_path), pagesize=letter)
            width, height = letter
            y = height - 50
            for line in markdown.splitlines():
                if y < 50:
                    c.showPage()
                    y = height - 50
                c.setFont("Helvetica", 9)
                c.drawString(40, y, line[:120])
                y -= 12
            c.save()
            return pdf_path
        except Exception as exc:  # noqa: BLE001
            logger.warning("PDF render skipped (%s)", exc)
            return None
